  on:
    pull_request:
      types:
        - opened
        - reopened
        - closed  # for merge PR
        - synchronize
      branches:
        - 'develop'
        - 'master'
    workflow_dispatch:

  env:
    AWS_REGION: ${{ secrets.NETFLOP_AWS_REGION }}
    AWS_ACCESS_KEY_ID: ${{ secrets.NETFLOP_AWS_ACCESS_KEY_ID }}
    AWS_SECRET_KEY: ${{ secrets.NETFLOP_AWS_SECRET_KEY }}
    ENVIRONMENT: ${{ github.base_ref == 'master' && 'prod' || 'dev' }}

  jobs:
    deploy-app:
      if: ${{ github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch' }}
      runs-on: ubuntu-latest
      steps:
        - name: Checkout latest code
          uses: actions/checkout@v4

        - name: Install AWS CLI
          run: |
            sudo apt-get update
            sudo apt-get install awscli

        - name: AWS Configuration
          run: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_KEY
            aws configure set default.region $AWS_REGION

        - name: Setup java 17
          uses: actions/setup-java@v3
          with:
            distribution: oracle
            java-version: 17

        - name: Setup Gradle
          uses: gradle/gradle-build-action@v2

        - name: Build project
          run: gradle task buildZip

        - name: Set up Node
          uses: actions/setup-node@v3
          with:
            node-version: "18"

        - name: Install CDK
          run: |
            npm install -g aws-cdk

        - name: Deploy
          run: |
            cd cdk
            cdk synth -c env=$ENVIRONMENT
            cdk bootstrap
            cdk deploy