  on:
    pull_request:
      types:
        - opened
        - reopened
        - closed  # for merge PR
        - synchronize
      branches:
        - 'develop'
        - 'master'
    workflow_dispatch:

  env:
    AWS_REGION: ${{ secret.NETFLOP_AWS_REGION }}
    AWS_ACCESS_KEY_ID: ${{ secret.NETFLOP_AWS_REGION }}
    AWS_SECRET_KEY: ${{ secret.NETFLOP_AWS_SECRETKEY }}
    ENVIRONMENT: ${{ github.base_ref == 'master' && 'prod' || 'dev' }}

  jobs:
    deploy-app:
      if: github.event.pull_request.merged == true
      runs-on: ubuntu-latest
      steps:
        - name: Configure AWS
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-region: ${{ AWS_REGION }}
            aws-access-key-id: ${{ AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ AWS_SECRET_KEY }}

        - name: Setup java 17
          uses: actions/setup-java@v3
          with:
            distribution: oracle
            java-version: 17

        - name: Setup Gradle
          uses: gradle/gradle-build-action@v2

        - name: Execute Gradle build
          run: gradle task buildZip

        - name: Set up Node
          uses: actions/setup-node@v3
          with:
            node-version: "18"

        - name: Install CDK
          run: |
            npm install -g aws-cdk

        - name: Install package CDK
          run: |
            cd cdk
            mvn clean install

        - name: CDK synth
          run: cdk synth -c env=$ENVIRONMENT

#        - name: CDK bootstrap
#          run: cdk bootstrap
#
#        - name: Deploy
#          run: cdk deploy